[settings]
log_level = "error"
minimum_release_age = "24h"
terminal_progress = true
not_found_auto_install = false

[tools]
actionlint = "latest"
amazon-ecr-credential-helper = "latest"
ansible = "latest"
ast-grep = "latest"
aws-iam-authenticator = "latest"
awscli = { version = "latest" }
azure = { version = "latest" }
azure-functions-core-tools = "latest"
azure-kubelogin = "latest"
bat = "latest"
checkov = "latest"
cilium-cli = "latest"
codex = "latest"
docker-cli = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
github-cli = "latest"
gitleaks = "latest"
go = "latest"
helm = "latest"
helm-docs = "latest"
java = "latest"
jq = "latest"
kind = "latest"
kubectx = "latest"
kubens = "latest"
kustomize = "latest"
lazygit = "latest"
lua = { version = "latest"}
mermaid-ascii = "latest"
neovim = "latest"
node = "latest"
pipx = "latest"
pre-commit = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
stylua = "latest"
talosctl = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
tflint = "latest"
tfsec = "latest"
tree-sitter = "latest"
trivy = "latest"
viddy = "latest"
yq = "latest"
