[tools]
"npm:@mermaid-js/mermaid-cli" = "latest"
"pipx:awslogs" = "latest"
"pipx:git-remote-codecommit" = "latest"
actionlint = "latest"
ansible = "latest"
ast-grep = "latest"
aws-iam-authenticator = "latest"
awscli = { version = "latest", symlink_bins = true }
azure-cli = "latest"
checkov = "latest"
cilium-cli = "latest"
gitleaks = "latest"
go = "latest"
helm = "latest"
kind = "latest"
kustomize = "latest"
node = "latest"
pre-commit = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
stylua = "latest"
talosctl = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
tfsec = "latest"
tflint = "latest"
tree-sitter = "latest"
trivy = "latest"
